### ISSUE TITLE
Nice project, How do I add another track

### ISSUE THREAD

**Issue by marriusco** [maximecb/Turing-Tunes#1]
Hi,
I am trying to add another track, and
tweaking MidiFileGenerator::outputToFile(),
but the new track is appended at the end after harmony+instrument is played.
Thank you.

**Comment by maximecb** [comment]
Hello. I'm not sure what you mean. There is no MidiFileGenerator in this repository.

**Comment by marriusco** [comment]
Sorry I used a wrong browser tab. Please close this thread.
